CREATE TABLE addresses
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street    VARCHAR(255),
    city      VARCHAR(100),
    state     VARCHAR(100),
    country   VARCHAR(100),
    zip_code  VARCHAR(20),
    latitude  DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    CONSTRAINT pk_addresses PRIMARY KEY (id)
);

CREATE TABLE properties
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    agent_id      BIGINT,
    title         VARCHAR(255)                            NOT NULL,
    description   TEXT,
    type          VARCHAR(50)                             NOT NULL,
    status        VARCHAR(20)                             NOT NULL,
    listing_type  VARCHAR(10),
    bedrooms      INTEGER,
    bathrooms     INTEGER,
    area_sqm      DECIMAL(10, 2),
    floor         INTEGER,
    total_floors  INTEGER,
    year_built    INTEGER,
    price         DECIMAL(12, 2),
    currency      VARCHAR(10),
    price_per_sqm DECIMAL(10, 2),
    address_id    BIGINT,
    search_vector TSVECTOR,
    is_featured   BOOLEAN,
    view_count    INTEGER,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    deleted_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_properties PRIMARY KEY (id)
);

CREATE TABLE property_features
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id BIGINT                                  NOT NULL,
    feature     VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_property_features PRIMARY KEY (id)
);

CREATE TABLE property_images
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id BIGINT                                  NOT NULL,
    image_url   VARCHAR(500)                            NOT NULL,
    caption     VARCHAR(255),
    sort_order  INTEGER,
    is_primary  BOOLEAN,
    CONSTRAINT pk_property_images PRIMARY KEY (id)
);

CREATE TABLE property_price_history
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id BIGINT                                  NOT NULL,
    old_price   DECIMAL(12, 2),
    new_price   DECIMAL(12, 2)                          NOT NULL,
    currency    VARCHAR(10),
    changed_by  BIGINT,
    reason      VARCHAR(255),
    changed_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_property_price_history PRIMARY KEY (id)
);

CREATE TABLE property_views
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id BIGINT                                  NOT NULL,
    user_id     BIGINT,
    ip_address  VARCHAR(45),
    user_agent  VARCHAR(255),
    viewed_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_property_views PRIMARY KEY (id)
);

CREATE TABLE sale_contracts
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id       BIGINT,
    listing_id        BIGINT,
    buyer_id          BIGINT,
    agent_id          BIGINT,
    sale_price        DECIMAL(12, 2),
    currency          VARCHAR(10),
    contract_date     date,
    handover_date     date,
    contract_file_url VARCHAR(500),
    status            VARCHAR(20),
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_sale_contracts PRIMARY KEY (id)
);

CREATE TABLE sale_listings
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id BIGINT,
    agent_id    BIGINT,
    price       DECIMAL(12, 2),
    currency    VARCHAR(10),
    negotiable  BOOLEAN,
    description TEXT,
    highlights  TEXT,
    status      VARCHAR(20),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_sale_listings PRIMARY KEY (id)
);

CREATE TABLE sale_payments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    contract_id     BIGINT,
    amount          DECIMAL(12, 2),
    currency        VARCHAR(10),
    payment_type    VARCHAR(30),
    paid_date       date,
    payment_method  VARCHAR(50),
    transaction_ref VARCHAR(255),
    status          VARCHAR(20),
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_sale_payments PRIMARY KEY (id)
);

CREATE TABLE saved_properties
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    property_id BIGINT                                  NOT NULL,
    note        TEXT,
    saved_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_saved_properties PRIMARY KEY (id)
);

ALTER TABLE property_features
    ADD CONSTRAINT idx_features_unique UNIQUE (property_id, feature);

ALTER TABLE saved_properties
    ADD CONSTRAINT uq_saved_user_property UNIQUE (user_id, property_id);

CREATE INDEX idx_price_history_date ON property_price_history (changed_at);

CREATE INDEX idx_prop_bedrooms ON properties (bedrooms);

CREATE INDEX idx_prop_listing ON properties (listing_type);

CREATE INDEX idx_prop_price ON properties (price);

CREATE INDEX idx_prop_status ON properties (status);

CREATE INDEX idx_prop_type ON properties (type);

CREATE INDEX idx_sale_contract_buyer ON sale_contracts (buyer_id);

CREATE INDEX idx_sale_contract_status ON sale_contracts (status);

CREATE INDEX idx_sale_pay_status ON sale_payments (status);

CREATE INDEX idx_sale_price ON sale_listings (price);

CREATE INDEX idx_sale_status ON sale_listings (status);

CREATE INDEX idx_saved_user ON saved_properties (user_id);

CREATE INDEX idx_views_date ON property_views (viewed_at);

CREATE INDEX idx_views_user ON property_views (user_id);

ALTER TABLE properties
    ADD CONSTRAINT FK_PROPERTIES_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES addresses (id);

ALTER TABLE property_features
    ADD CONSTRAINT FK_PROPERTY_FEATURES_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES properties (id);

ALTER TABLE property_images
    ADD CONSTRAINT FK_PROPERTY_IMAGES_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES properties (id);

ALTER TABLE property_price_history
    ADD CONSTRAINT FK_PROPERTY_PRICE_HISTORY_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES properties (id);

CREATE INDEX idx_price_history_property ON property_price_history (property_id);

ALTER TABLE property_views
    ADD CONSTRAINT FK_PROPERTY_VIEWS_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES properties (id);

CREATE INDEX idx_views_property ON property_views (property_id);

ALTER TABLE sale_contracts
    ADD CONSTRAINT FK_SALE_CONTRACTS_ON_LISTING FOREIGN KEY (listing_id) REFERENCES sale_listings (id);

ALTER TABLE sale_contracts
    ADD CONSTRAINT FK_SALE_CONTRACTS_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES properties (id);

CREATE INDEX idx_sale_contract_property ON sale_contracts (property_id);

ALTER TABLE sale_listings
    ADD CONSTRAINT FK_SALE_LISTINGS_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES properties (id);

CREATE INDEX idx_sale_property ON sale_listings (property_id);

ALTER TABLE sale_payments
    ADD CONSTRAINT FK_SALE_PAYMENTS_ON_CONTRACT FOREIGN KEY (contract_id) REFERENCES sale_contracts (id);

CREATE INDEX idx_sale_pay_contract ON sale_payments (contract_id);

ALTER TABLE saved_properties
    ADD CONSTRAINT FK_SAVED_PROPERTIES_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES properties (id);

CREATE INDEX idx_saved_property ON saved_properties (property_id);
