CREATE TABLE agent_profiles
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    phone            VARCHAR(30),
    license          VARCHAR(100),
    bio              TEXT,
    experience_years INTEGER,
    specialization   VARCHAR(100),
    photo_url        VARCHAR(500),
    rating           DECIMAL(3, 2),
    total_reviews    INTEGER,
    CONSTRAINT pk_agent_profiles PRIMARY KEY (id)
);

CREATE TABLE client_profiles
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id           BIGINT                                  NOT NULL,
    phone             VARCHAR(30),
    preferred_contact VARCHAR(20),
    budget_min        DECIMAL(12, 2),
    budget_max        DECIMAL(12, 2),
    preferred_type    VARCHAR(50),
    preferred_city    VARCHAR(100),
    photo_url         VARCHAR(500),
    CONSTRAINT pk_client_profiles PRIMARY KEY (id)
);

CREATE TABLE property_lead_requests
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id         BIGINT,
    assigned_agent_id BIGINT,
    property_id       BIGINT,
    type              VARCHAR(20),
    message           TEXT,
    budget            DECIMAL(12, 2),
    preferred_date    date,
    source            VARCHAR(50),
    status            VARCHAR(20),
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_property_lead_requests PRIMARY KEY (id)
);

ALTER TABLE agent_profiles
    ADD CONSTRAINT uc_agent_profiles_user UNIQUE (user_id);

ALTER TABLE client_profiles
    ADD CONSTRAINT uc_client_profiles_user UNIQUE (user_id);

CREATE INDEX idx_leads_agent ON property_lead_requests (assigned_agent_id);

CREATE INDEX idx_leads_client ON property_lead_requests (client_id);

CREATE INDEX idx_leads_status ON property_lead_requests (status);

ALTER TABLE property_lead_requests
    ADD CONSTRAINT FK_PROPERTY_LEAD_REQUESTS_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES properties (id);
