CREATE TABLE lease_contracts
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id       BIGINT,
    listing_id        BIGINT,
    client_id         BIGINT,
    agent_id          BIGINT,
    start_date        date,
    end_date          date,
    rent              DECIMAL(12, 2),
    deposit           DECIMAL(12, 2),
    currency          VARCHAR(10),
    contract_file_url VARCHAR(500),
    status            VARCHAR(20),
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_lease_contracts PRIMARY KEY (id)
);

CREATE TABLE payments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    contract_id     BIGINT,
    amount          DECIMAL(12, 2),
    currency        VARCHAR(10),
    payment_type    VARCHAR(30),
    due_date        date,
    paid_date       date,
    payment_method  VARCHAR(50),
    transaction_ref VARCHAR(255),
    status          VARCHAR(20),
    notes           TEXT,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

CREATE TABLE rental_applications
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    listing_id       BIGINT,
    client_id        BIGINT,
    status           VARCHAR(20),
    message          TEXT,
    income           DECIMAL(12, 2),
    move_in_date     date,
    reviewed_by      BIGINT,
    reviewed_at      TIMESTAMP WITHOUT TIME ZONE,
    rejection_reason TEXT,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_rental_applications PRIMARY KEY (id)
);

CREATE TABLE rental_listings
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id      BIGINT                                  NOT NULL,
    agent_id         BIGINT,
    title            VARCHAR(255),
    description      TEXT,
    available_from   date,
    available_until  date,
    price            DECIMAL(12, 2),
    currency         VARCHAR(10),
    deposit          DECIMAL(12, 2),
    price_period     VARCHAR(20),
    min_lease_months INTEGER,
    status           VARCHAR(20),
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    deleted_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_rental_listings PRIMARY KEY (id)
);

CREATE INDEX idx_lease_client ON lease_contracts (client_id);

CREATE INDEX idx_lease_status ON lease_contracts (status);

CREATE INDEX idx_payments_due_date ON payments (due_date);

CREATE INDEX idx_payments_status ON payments (status);

CREATE INDEX idx_rental_app_client ON rental_applications (client_id);

CREATE INDEX idx_rental_app_status ON rental_applications (status);

CREATE INDEX idx_rental_price ON rental_listings (price);

CREATE INDEX idx_rental_status ON rental_listings (status);

ALTER TABLE lease_contracts
    ADD CONSTRAINT FK_LEASE_CONTRACTS_ON_LISTING FOREIGN KEY (listing_id) REFERENCES rental_listings (id);

ALTER TABLE lease_contracts
    ADD CONSTRAINT FK_LEASE_CONTRACTS_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES properties (id);

CREATE INDEX idx_lease_property ON lease_contracts (property_id);

ALTER TABLE payments
    ADD CONSTRAINT FK_PAYMENTS_ON_CONTRACT FOREIGN KEY (contract_id) REFERENCES lease_contracts (id);

CREATE INDEX idx_payments_contract ON payments (contract_id);

ALTER TABLE rental_applications
    ADD CONSTRAINT FK_RENTAL_APPLICATIONS_ON_LISTING FOREIGN KEY (listing_id) REFERENCES rental_listings (id);

CREATE INDEX idx_rental_app_listing ON rental_applications (listing_id);

ALTER TABLE rental_listings
    ADD CONSTRAINT FK_RENTAL_LISTINGS_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES properties (id);

CREATE INDEX idx_rental_property ON rental_listings (property_id);