CREATE TABLE maintenance_requests
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id    BIGINT,
    lease_id       BIGINT,
    requested_by   BIGINT,
    assigned_to    BIGINT,
    title          VARCHAR(255),
    description    TEXT,
    category       VARCHAR(50),
    priority       VARCHAR(20),
    status         VARCHAR(20),
    estimated_cost DECIMAL(10, 2),
    actual_cost    DECIMAL(10, 2),
    completed_at   TIMESTAMP WITHOUT TIME ZONE,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_maintenance_requests PRIMARY KEY (id)
);

CREATE TABLE notifications
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id             BIGINT,
    title               VARCHAR(255),
    message             TEXT,
    type                VARCHAR(50),
    related_entity_type VARCHAR(100),
    related_entity_id   BIGINT,
    action_url          VARCHAR(500),
    is_read             BOOLEAN,
    read_at             TIMESTAMP WITHOUT TIME ZONE,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

CREATE INDEX idx_maintenance_status ON maintenance_requests (status);

CREATE INDEX idx_notif_is_read ON notifications (user_id, is_read);

CREATE INDEX idx_notif_user ON notifications (user_id);

ALTER TABLE maintenance_requests
    ADD CONSTRAINT FK_MAINTENANCE_REQUESTS_ON_LEASE FOREIGN KEY (lease_id) REFERENCES lease_contracts (id);

ALTER TABLE maintenance_requests
    ADD CONSTRAINT FK_MAINTENANCE_REQUESTS_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES properties (id);

CREATE INDEX idx_maintenance_property ON maintenance_requests (property_id);