CREATE TABLE sale_applications
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    listing_id            BIGINT         NULL,
    property_id           BIGINT         NULL,
    buyer_id              BIGINT         NOT NULL,
    agent_id              BIGINT         NULL,
    message               TEXT           NULL,
    offer_price           DECIMAL(12, 2) NULL,
    desired_purchase_date date           NULL,
    monthly_income        DECIMAL(12, 2) NULL,
    status                VARCHAR(20)    NULL,
    rejection_reason      TEXT           NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE      NULL,
    updated_at            TIMESTAMP WITHOUT TIME ZONE       NULL,
    CONSTRAINT pk_sale_applications PRIMARY KEY (id)
);

CREATE INDEX idx_sale_app_buyer ON sale_applications (buyer_id);

CREATE INDEX idx_sale_app_status ON sale_applications (status);

ALTER TABLE sale_applications
    ADD CONSTRAINT FK_SALE_APPLICATIONS_ON_LISTING FOREIGN KEY (listing_id) REFERENCES sale_listings (id);

CREATE INDEX idx_sale_app_listing ON sale_applications (listing_id);

ALTER TABLE sale_applications
    ADD CONSTRAINT FK_SALE_APPLICATIONS_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES properties (id);

CREATE INDEX idx_sale_app_property ON sale_applications (property_id);
