CREATE TABLE notifications
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id             BIGINT       NULL,
    title               VARCHAR(255) NULL,
    message             TEXT         NULL,
    type                VARCHAR(50)  NULL,
    related_entity_type VARCHAR(100) NULL,
    related_entity_id   BIGINT       NULL,
    action_url          VARCHAR(500) NULL,
    is_read             BIT(1)       NULL,
    read_at             TIMESTAMP WITHOUT TIME ZONE     NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE     NULL,
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

CREATE INDEX idx_notif_is_read ON notifications (user_id, is_read);

CREATE INDEX idx_notif_user ON notifications (user_id);
