CREATE TABLE maintenance_requests
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id    BIGINT         NULL,
    lease_id       BIGINT         NULL,
    requested_by   BIGINT         NULL,
    assigned_to    BIGINT         NULL,
    title          VARCHAR(255)   NULL,
    description    TEXT           NULL,
    category       VARCHAR(50)    NULL,
    priority       VARCHAR(20)    NULL,
    status         VARCHAR(20)    NULL,
    estimated_cost DECIMAL(10, 2) NULL,
    actual_cost    DECIMAL(10, 2) NULL,
    completed_at   TIMESTAMP WITHOUT TIME ZONE       NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE       NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE       NULL,
    CONSTRAINT pk_maintenance_requests PRIMARY KEY (id)
);

CREATE INDEX idx_maintenance_status ON maintenance_requests (status);

ALTER TABLE maintenance_requests
    ADD CONSTRAINT FK_MAINTENANCE_REQUESTS_ON_LEASE FOREIGN KEY (lease_id) REFERENCES lease_contracts (id);

ALTER TABLE maintenance_requests
    ADD CONSTRAINT FK_MAINTENANCE_REQUESTS_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES properties (id);

CREATE INDEX idx_maintenance_property ON maintenance_requests (property_id);
