CREATE TABLE public.refresh_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    token      VARCHAR(512)                            NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    revoked    BOOLEAN                                 NOT NULL,
    ip_address VARCHAR(45),
    user_agent VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

CREATE TABLE public.tenant_schema_registry
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id      BIGINT                                  NOT NULL,
    schema_name    VARCHAR(63)                             NOT NULL,
    is_provisioned BOOLEAN                                 NOT NULL,
    provisioned_at TIMESTAMP WITHOUT TIME ZONE,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tenant_schema_registry PRIMARY KEY (id)
);

CREATE TABLE public.tenants_company
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    slug       VARCHAR(63)                             NOT NULL,
    plan       VARCHAR(20)                             NOT NULL,
    is_active  BOOLEAN                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tenants_company PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(150)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    first_name VARCHAR(50),
    last_name  VARCHAR(50),
    role       VARCHAR(20)                             NOT NULL,
    tenant_id  BIGINT                                  NOT NULL,
    is_active  BOOLEAN                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE public.refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_token UNIQUE (token);

ALTER TABLE public.tenant_schema_registry
    ADD CONSTRAINT uc_tenant_schema_registry_schema_name UNIQUE (schema_name);

ALTER TABLE public.tenant_schema_registry
    ADD CONSTRAINT uc_tenant_schema_registry_tenant UNIQUE (tenant_id);

ALTER TABLE public.tenants_company
    ADD CONSTRAINT uc_tenants_company_name UNIQUE (name);

ALTER TABLE public.tenants_company
    ADD CONSTRAINT uc_tenants_company_slug UNIQUE (slug);

ALTER TABLE public.users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

CREATE INDEX idx_refresh_token ON public.refresh_tokens (token);

CREATE INDEX idx_schema_registry_name ON public.tenant_schema_registry (schema_name);

CREATE INDEX idx_tenant_slug ON public.tenants_company (slug);

CREATE INDEX idx_user_email ON public.users (email);

ALTER TABLE public.refresh_tokens
    ADD CONSTRAINT FK_REFRESH_USER FOREIGN KEY (user_id) REFERENCES public.users (id);

CREATE INDEX idx_refresh_user ON public.refresh_tokens (user_id);

ALTER TABLE public.tenant_schema_registry
    ADD CONSTRAINT FK_SCHEMA_REGISTRY_TENANT FOREIGN KEY (tenant_id) REFERENCES public.tenants_company (id);

CREATE INDEX idx_schema_registry_tenant ON public.tenant_schema_registry (tenant_id);

ALTER TABLE public.users
    ADD CONSTRAINT FK_USERS_ON_TENANT FOREIGN KEY (tenant_id) REFERENCES public.tenants_company (id);

CREATE INDEX idx_user_tenant ON public.users (tenant_id);